offset = 700;

dialog_init();

dialog_add(noone, "A tale of the legendary dragon slayer Ruo family");
dialog_add(noone, "The Princess Ruo Lian, Keeper of The Sword");
dialog_add(noone, "Her right hand, Qiu Ye");
dialog_add(noone, "Or something more");
dialog_add(noone, "They would tell her to conceal her emotions");
dialog_add(noone, "That purity could even contain the devil");
dialog_add(noone, "Did you scream? The nightmares again, Dianxia?");
dialog_add(noone, "Dianxa you cannot destory the blade, it is your legacy");
dialog_add(noone, "Your purity will protect us from the evil sealed within");
dialog_add(noone, "Please...");
dialog_add(noone, "Save...");
dialog_add(noone, "Me!");
dialog_add(noone, " ");
dialog_add(noone, " ");
dialog_add(noone, " ");
dialog_add(noone, "");
dialog_add(noone, "I tried, I promise");
dialog_add(noone, "I'm sorry...");
dialog_add(noone, " ");
dialog_add(noone, "I miss you everyday");
dialog_add(noone, "Your legacy");
dialog_add(noone, "Our future");
dialog_add(noone, "I won't let you die in vain");
dialog_add(noone, "I, Qiu Ye");
dialog_add(noone, "Swear to you");
dialog_add(noone, "My unyielding devotion");
dialog_add(noone, "Beyond life...!");
dialog_reset();
